
CREATE DATABASE IF NOT EXISTS P5_Pur_Beurre CHARACTER SET 'utf8';
USE P5_Pur_Beurre;


CREATE TABLE IF NOT EXISTS Food (
    id SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
    Category VARCHAR(255) NULL,
    Food_Name CHAR(255) NULL,
    Generic_Name VARCHAR(255) NULL,
    Brand CHAR(255) NULL,
    Stores VARCHAR(255) NULL,
    Link VARCHAR(255) NULL,
    Nutrigrade VARCHAR(5) NULL,
    PRIMARY KEY (id)
)
ENGINE=INNODB;


CREATE TABLE IF NOT EXISTS Favorites (
    id SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
    UserID SMALLINT NOT NULL,
    FoodID SMALLINT NOT NULL,
    PRIMARY KEY (id)
)
ENGINE=INNODB;


CREATE TABLE IF NOT EXISTS Users (
    id SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
    UserName CHAR(255) NOT NULL,
    PRIMARY KEY (id)
)
ENGINE=INNODB;
