
CREATE DATABASE IF NOT EXISTS P5_Pur_Beurre CHARACTER SET 'utf8';
USE P5_Pur_Beurre;


DROP TABLE IF EXISTS Food;
CREATE TABLE Food (
    id SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
    Category VARCHAR(255) NOT NULL,
    Food_Name CHAR(255) NOT NULL,
    Generic_Name VARCHAR(255) NULL,
    Brand CHAR(255) NULL,
    Stores VARCHAR(255) NULL,
    Link VARCHAR(255) NOT NULL,
    Nutrigrade VARCHAR(5) NOT NULL,
    PRIMARY KEY (id)
)
ENGINE=INNODB;

DROP TABLE IF EXISTS Favorites;
CREATE TABLE Favorites (
    id SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
    UserID SMALLINT NOT NULL,
    FoodID SMALLINT NOT NULL,
    PRIMARY KEY (id)
)
ENGINE=INNODB;


CREATE TABLE IF NOT EXISTS Users (
    id SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
    UserName VARCHAR(255) NOT NULL,
    UserPassword VARCHAR(255) NULL,
    PRIMARY KEY (id)
)
ENGINE=INNODB;
